export enum EditorMode {
  SELECT = "SELECT",
  PLATFORM = "PLATFORM",
  SOLID_BLOCK = "SOLID_BLOCK",
  DIAGONAL_PLATFORM = "DIAGONAL_PLATFORM",
  MEMORY_CRYSTAL = "MEMORY_CRYSTAL",
  GHOST = "GHOST",
  LANDGHOST = "LANDGHOST",
  PLAYER = "PLAYER",
  DELETE = "DELETE",
  AREA_SELECT = "AREA_SELECT",
}
